const {checkToken} = require('../../token/token.validation')

const router = require('express').Router()
const {registerUserController, loginUserController,searchedItemsSortByDateController,searchedItemsSortByNameController, viewItemController,claimByUserController,searchProductController,addReportController,viewProductByOrderDate,viewProductByName,tokenCheckerController,viewReportController,lostItemFoundController,viewReportCategoriesController} = require('./user.controller')
router.post("/login",loginUserController)
router.get("/d",checkToken,viewProductByOrderDate)
router.get("/n",checkToken,viewProductByName)
router.get("/",viewItemController)
router.post("/tokenCheck",checkToken,tokenCheckerController)
router.post('/',checkToken,claimByUserController)
router.post("/register",registerUserController)
router.post("/search",checkToken,searchProductController)
router.post("/report",checkToken,addReportController)
router.post("/reportG",checkToken,viewReportController)
router.post("/searchD",checkToken,searchedItemsSortByDateController)
router.post("/searchN",checkToken,searchedItemsSortByNameController)
router.post("/reportFound",checkToken,lostItemFoundController)
router.get("/reportCategories",viewReportCategoriesController)
module.exports = router